[tool.kedro]
package_name = "variational_auto_encoder_to_generate_new_data"
project_name = "variational_auto_encoder_to_generate_new_data"
kedro_init_version = "0.18.12"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/variational_auto_encoder_to_generate_new_data -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
